routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Mail\MessageReceived;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

ini_set('memory_limit', '-1');
set_time_limit(0);

Auth::routes();

Route::get('/', function () {
    $existSession =Auth::user();
    if(is_null($existSession) ) {
        return view('main_admin.login');
    } else {
        return redirect('main_admin');
    }
});

/* Ruta del login */
Route::get('/laboratorio_sspcdmx', function () {
    $existSession = Auth::user();
    if(is_null($existSession) ) {
        return view('main_admin.login');
    } else {
        return redirect('main_admin');
    }

})->name('laboratorio_sspcdmx');

/* Ruta para acceder al panel principal */
Route::resource('main_admin', 'MainController');

Route::group(['middleware' => 'users'], function () {
    /* Ruta para CRUD de usuarios */
    Route::get('dataTableUsers', 'UsersController@dataTableU')->name('dataTableUsers');

    Route::resource('usuarios', 'UsersController');

});

/* Ruta para CRUD de datos pacientes*/
/* Route::resource('datos', 'DatosFederalesController'); */
Route::group(['middleware' => 'admin'], function () {

        /* Ruta index Datos Federales*/
    Route::get('datos/{tipo}', 'DatosFederalesController@index');

        /* Ruta para destroy de datos */
    Route::delete('datos/{datos}', 'DatosFederalesController@destroy')->name('datos.destroy');

});


Route::get('dataTableDatos', 'DatosFederalesController@dataTable')->name('dataTableDatos');

Route::patch('datos/{dato}/cancelado', 'DatosFederalesController@cancelado')->name('datos.cancelado');

Route::patch('datos/{dato}/pendiente', 'DatosFederalesController@pendiente')->name('datos.pendiente');

Route::patch('datos/{dato}/finalizado', 'DatosFederalesController@finalizado')->name('datos.finalizado');

Route::get('privilegios', function () {
    return view('errors.404');
});

Route::put('estados', 'DatosFederalesController@changeEstados');

//Rutas para reportes
Route::resource('/reportes', 'ReportesController' );

//Ruta index para proceso de asignación de resultados
Route::get('allocation', 'AllocationResultsController@index')->name('allocation');

Route::get('dataTableAsignaciones', 'AllocationResultsController@dataTableR')->name('dataTableAsignaciones');

//Ruta index para el log de modificaciones
Route::get('log', 'LogController@index')->name('log');

Route::get('dataTableLog', 'LogController@dataTableLogChanges')->name('dataTableLog');

Route::get('search/muestra/{id}', 'AllocationResultsController@searchMuestra');

Route::get('search/result/{id}', 'AllocationResultsController@edit');

Route::get('search/kit', 'AllocationResultsController@searchDiagnosisForKit');

Route::post('allocation', 'AllocationResultsController@store')->name('allocation');

Route::put('allocation/{id}', 'AllocationResultsController@update');

Route::resource('/results', 'ResultsController');

Route::resource('/destinatarios', 'DestinatariosController');

Route::get('dataTableDestinatarios', 'DestinatariosController@BuildDataTable')->name('dataTableADestinatarios');
/* Route::get('/import-form', 'DatosFederalesController@importForm');
Route::post('import', 'DatosFederalesController@import')->name('datos.import'); */

Route::get('full', 'FullResultsController@index')->name('full');
Route::get('dataTableFull', 'FullResultsController@dataTableFullResults')->name('dataTableFull');

Route::get('query', 'QueryResultsController@index')->name('query');
Route::get('dataTableQuery', 'QueryResultsController@dataTableQueryResults')->name('dataTableQuery');

Route::put('operational/status', 'DatosFederalesController@changeOperationalEstados');

Route::get('export/jurisdiction/{id}', 'QueryResultsController@exportJurisdiction');

Route::get('descarga', 'MainController@downloadGeneral');

Route::prefix('grafica')->group(function() {
    Route::get('/ingresadas', 'ViewChartController@ingresadas');

    Route::get('/rechazadas', 'ViewChartController@rechazadas');

    Route::get('/motivos', 'ViewChartController@motivos');

    Route::get('/jurisdicciones', 'ViewChartController@jurisdicciones');

    Route::get('/hospitales', 'ViewChartController@hospitales');

    Route::get('/muestras', 'ViewChartController@muestras');

    Route::get('/recepcionadas', 'ViewChartController@recepcionadas');
});

Route::prefix('diagnostico')->group(function () {
    Route::get('/respiratorios', 'DiagnosticsController@respiratorio');

});

Route::get('paludismo', 'PaludismoController')->name('paludismo.index');

app/Users.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Users extends Model
{
    protected $fillable = [

        'id_role', 'username', 'name', 'paternal_surname', 'maternal_surname', 'id_juris', 'id_areas', 'phone', 'ext', 'email', 'password'  

    ];
    
    protected $hidden = [

        'password', 'remember_token',

    ];

    public function areas(){

        return $this->belongsTo(Area::class, 'id_areas');

    }

    public function juris(){

        return $this->belongsTo(Juri::class, 'id_juris');

    }

    public function role(){

        return $this->belongsTo(Role::class, 'id_role');

    }

    public function DatosFederales(){

        return $this->hasMany(DatosFederales::class);

    }

    public function scopeBuscador($query, $usuario){

        if ($usuario != ""){

            $query->where(\DB::raw("CONCAT(username, ' ', name, ' ', paternal_surname, ' ', maternal_surname, ' ', phone, ' ', ext, ' ', email)"), "LIKE", "%$usuario%");
            /* $query->where('admin_unit', "LIKE", "%$volante%"); */

        }

    }

    public function getFullNameAttribute() {
        return $this->name.' '.$this->paternal_surname.' '.$this->maternal_surname;
    }
}

app/Http/Livewire/Downloads/ResultsDownloads.php
<?php

namespace App\Http\Livewire\Downloads;

use App\Exports\ResultsExport;
use Livewire\Component;

use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\DB;

class ResultsDownloads extends Component
{
    public $date_start, $date_end;

    public function render()
    {
        return view('livewire.downloads.results-downloads');
    }

    public function submit()
    {
        $this->resetErrorBag();
        $this->resetValidation();
        $this->validate([
            'date_start' => ['required', 'regex:/^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/'],
            'date_end' => ['required', 'regex:/^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/'],
        ]);
        $start = Carbon::createFromFormat('d/m/Y', $this->date_start);
        $end = Carbon::createFromFormat('d/m/Y', $this->date_end);

        $filename = "Reporte-general-de-resultados-" . date('dmYHis') . ".xlsx";
        $title = "Reporte general de resultados";

        $searchData = DB::table('view_full_results')
        ->join('users', 'view_full_results.user_register_result', '=', 'users.id')
        ->whereBetween('view_full_results.fecha_recepcion', [$start->toDateString(), $end->toDateString()])
        ->get();
        return Excel::download(new ResultsExport($title, $searchData), $filename);
    }
}

app/Http/Livewire/Downloads/SamplesDownloads.php
<?php

namespace App\Http\Livewire\Downloads;

use App\DatosFederales;
use App\Exports\SamplesExport;
use Livewire\Component;

use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\DB;

class SamplesDownloads extends Component
{

    public $date_start, $date_end;

    public function render()
    {
        return view('livewire.downloads.samples-downloads');
    }

    public function submit()
    {
        $this->resetErrorBag();
        $this->resetValidation();

        $this->validate([
            'date_start' => ['required', 'regex:/^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/'],
            'date_end' => ['required', 'regex:/^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/'],
        ]);
        $start = Carbon::createFromFormat('d/m/Y', $this->date_start);
        $end = Carbon::createFromFormat('d/m/Y', $this->date_end);

        $filename = "Reporte-de-muestras-recibidas-" . date('dmYHis') . ".xlsx";
        $title = "Reporte general de muestras recibidas";

        $searchData = DatosFederales::where('is_active', 1)->whereBetween('fecha_recepcion', [$start->toDateString(), $end->toDateString()])->orderBy('folio_lesp', 'ASC')->get();
        return Excel::download(new SamplesExport($title, $searchData), $filename );
    }
}

resources/views/main_admin/downloads/index.blade.php
@extends('layouts.panel')
@section('content')
<div id="container-component" class="p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 flex justify-center items-center flex-col">
    <div class="row">
        
        @if(Auth::user()->id_role == 1 or Auth::user()->id_role == 3 or Auth::user()->id_role == 6 or Auth::user()->id == 18 or Auth::user()->id_role == 11)
            <fieldset class="border mt-3 mb-6 p-2 w-full lg:w-11/12 xl:w-3/4 2xl:max-w-4xl">
                <legend class="px-2 mb-2 text-sm xl:text-lg font-semibold tracking-tight text-green-800 dark:text-white">Reporte general de muestras</legend>
                <livewire:downloads.samples-downloads />
            </fieldset>
        @endif

        @if(Auth::user()->id_role == 1 or Auth::user()->id_role == 5 or Auth::user()->id_role == 6 or Auth::user()->id == 18 or Auth::user()->id_role == 11)
        <fieldset class="border mt-3 mb-6 p-2 w-full lg:w-11/12 xl:w-3/4 2xl:max-w-4xl">
            <legend class="px-2 mb-2 text-sm xl:text-lg font-semibold tracking-tight text-green-800 dark:text-white">Reporte general de resultados</legend>
            <livewire:downloads.results-downloads />
        </fieldset>
        @endif
    </div>
</div>
<br>
<br>
@endsection

resources/views/main_admin/downloads/result-export.blade.php
<table>

    <tr>
        <td></td>
        <td colspan="4">{{ $title }}</td>
    </tr>
    <tr>
        <td></td>
        <td colspan="2">Fecha de exportación:</td>
        <td colspan="2">{{ \Carbon\Carbon::now()->isoFormat('D MMM YYYY, h:mm A') }}</td>
    </tr>

    <tr></tr>
    <tr>
        <td>indice</td>
        <td>año</td>
        <td>Folio LESP</td>
        <td>dx1</td>
        <td>dx2</td>
        <td>dx3</td>
        <td>dx4</td>
        <td>dx5</td>
        <td>Oficio de Entrada</td>
        <td>Nombre del Paciente</td>
        <td>Tipo de Muestra</td>
        <td>Fecha de Toma de Muestra</td>
        <td>Folio SINAVE</td>
        <td>Estatus REMU</td>
        <td>Estatus Resultado</td>
        <td># CRE/FORMATO/BITACORA</td>
        <td>Comentarios Adicionales</td>
        <td>Interpretación del Resultado</td>
        <td>Oficio de salida</td>
        <td>Fecha de entrega al AEER</td>
        <td>Diagnostico solicitado</td>
        <td>Kit empleado</td>
        <td>Valor de referencia</td>
        <td>Técnica empleada</td>
        <td>Analisis</td>
        <td>Resultado</td>
        <td>Nombre del Usuario que registro</td>
        <td>Fecha</td>
    </tr>
    <tbody>
        @php
        $index = 1;
        @endphp

        @foreach ($samples as $sample )
        <tr>
            <td>{{$index}}</td>
            <td>{{$sample->anio}}</td>
            <td>{{$sample->folio_lesp}}</td>
            <td>{{$sample->dx1}}</td>
            <td>{{$sample->dx2}}</td>
            <td>{{$sample->dx3}}</td>
            <td>{{$sample->dx4}}</td>
            <td>{{$sample->dx5}}</td>
            <td>{{$sample->oficio_entrada}}</td>
            <td>{{$sample->nombre_paciente}}</td>
            <td>{{$sample->tipo_muestra}}</td>
            <td>{{$sample->fecha_toma_muestra}}</td>
            <td>{{$sample->folio_sisver}}</td>
            <td>{{$sample->status}}</td>
            <td>{{$sample->status_result}}</td>
            <td>{{$sample->cre}}</td>
            <td>{{$sample->result_comments}}</td>
            <td>{{$sample->interpretation_result}}</td>
            <td>{{$sample->if_exit}}</td>
            <td>{{$sample->date_delivery}}</td>
            <td>{{$sample->diagnosis_name}}</td>
            <td>{{$sample->kit_name}}</td>
            <td>{{$sample->reference_value}}</td>
            <td>{{$sample->technique_name}}</td>
            <td>{{$sample->analysis}}</td>
            <td>{{$sample->result}}</td>
            <td>{{$sample->name.' '.$sample->paternal_surname.' '.$sample->maternal_surname}}</td>
            <td>{{$sample->fecha_recepcion}}</td>
        </tr>

        @php
        $index++;
        @endphp

        @endforeach
    </tbody>
</table>

resources/views/main_admin/downloads/samples-export.blade.php
<table>

    <tr>
        <td></td>
        <td colspan="4">{{ $title }}</td>
    </tr>
    <tr>
        <td></td>
        <td colspan="2">Fecha de exportación:</td>
        <td colspan="2">{{ \Carbon\Carbon::now()->isoFormat('D MMM YYYY, h:mm A') }}</td>
    </tr>

    <tr></tr>
    <tr>
        <td>indice</td>
        <td>año</td>
        <td>Folio LESP</td>
        <td>dx1</td>
        <td>dx2</td>
        <td>dx3</td>
        <td>dx4</td>
        <td>dx5</td>
        <td>Oficio de Entrada</td>
        <td>Fecha de Recepción</td>
        <td>Jurisdicción/Hospital</td>
        <td>Nombre del Paciente</td>
        <td>Tipo de Muestra</td>
        <td>Fecha de Toma de Muestra</td>
        <td>Folio SISVER</td>
        <td>Persona que Recibe</td>
        <td>Estatus</td>
        <td>Rechazos</td>
        <td>Observaciones</td>
        <td>Aclaraciones Remu</td>
        <td>Hora de recepción</td>
        <td>Usuario que Registro</td>
        <td>Fecha</td>
    </tr>
    <tbody>
        @php
        $index = 1;
        @endphp

        @foreach ($samples as $sample )
        <tr>
            <td>{{$index}}</td>
            <td>{{$sample->anio}}</td>
            <td>{{$sample->folio_lesp}}</td>
            <td>{{$sample->dx1}}</td>
            <td>{{$sample->dx2}}</td>
            <td>{{$sample->dx3}}</td>
            <td>{{$sample->dx4}}</td>
            <td>{{$sample->dx5}}</td>
            <td>{{$sample->oficio_entrada}}</td>
            <td>{{$sample->fecha_recepcion}}</td>
            <td>{{$sample->hospital}}</td>
            <td>{{$sample->nombre_paciente}}</td>
            <td>{{$sample->tipo_muestra}}</td>
            <td>{{$sample->fecha_toma_muestra}}</td>
            <td>{{$sample->folio_sisver}}</td>
            <td>{{$sample->persona_recibe}}</td>
            <td>{{$sample->status}}</td>
            <td>{{$sample->rechazos}}</td>
            <td>{{$sample->observaciones}}</td>
            <td>{{$sample->aclaraciones_remu}}</td>
            <td>{{$sample->hora_recepcion}}</td>
            <td>{{$sample->users->full_name}}</td>
            <td>{{$sample->fecha_recepcion}}</td>
        </tr>

        @php
        $index++;
        @endphp

        @endforeach
    </tbody>
</table>